apiVersion: apps/v1
kind: Deployment
metadata:
  name: bulutistan-redis
  labels:
    app: bulutistan-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bulutistan-redis
  template:
    metadata:
      labels:
        app: bulutistan-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          args:
            - redis-server
            - --maxmemory
            - 256mb
            - --maxmemory-policy
            - allkeys-lru
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
