apiVersion: v1
kind: Service
metadata:
  name: bulutistan-redis
  labels:
    app: bulutistan-redis
spec:
  type: ClusterIP
  selector:
    app: bulutistan-redis
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
