CREATE USER infra_svc WITH PASSWORD 'InfraSvc@Bulut2026' NOSUPERUSER NOCREATEDB NOCREATEROLE;

CREATE USER customer_svc WITH PASSWORD 'CustomerSvc@Bulut2026' NOSUPERUSER NOCREATEDB NOCREATEROLE;

CREATE USER query_svc WITH PASSWORD 'QuerySvc@Bulut2026' NOSUPERUSER NOCREATEDB NOCREATEROLE;

GRANT USAGE ON SCHEMA public TO infra_svc;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO infra_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO infra_svc;

GRANT USAGE ON SCHEMA customer TO customer_svc;
GRANT SELECT ON ALL TABLES IN SCHEMA customer TO customer_svc;

GRANT USAGE ON SCHEMA public TO query_svc;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO query_svc;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO query_svc;
