CREATE TABLE public.cluster_metrics (
	datacenter text NULL,
	"cluster" text NULL,
	"timestamp" timestamp NULL,
	vhost_count int4 NULL,
	vm_count int4 NULL,
	cpu_ghz_capacity numeric(10, 2) NULL,
	cpu_ghz_used numeric(10, 2) NULL,
	cpu_ghz_free numeric(10, 2) NULL,
	memory_capacity_gb numeric(10, 2) NULL,
	memory_used_gb numeric(10, 2) NULL,
	memory_free_gb numeric(10, 2) NULL,
	disk_usage_avg_kbps numeric(15, 2) NULL,
	disk_usage_min_kbps numeric(15) NULL,
	disk_usage_max_kbps numeric(15) NULL,
	network_usage_avg_kbps numeric(15, 2) NULL,
	network_usage_min_kbps numeric(15) NULL,
	network_usage_max_kbps numeric(15) NULL,
	memory_usage_avg_perc numeric(7, 2) NULL,
	memory_usage_min_perc numeric(7, 2) NULL,
	memory_usage_max_perc numeric(7, 2) NULL,
	cpu_usage_avg_perc numeric(7, 2) NULL,
	cpu_usage_min_perc numeric(7, 2) NULL,
	cpu_usage_max_perc numeric(7, 2) NULL,
	total_freespace_gb numeric(20, 2) NULL,
	total_capacity_gb numeric(20, 2) NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT unique_cluster_timestamp UNIQUE (datacenter, cluster, "timestamp")
);
CREATE INDEX idx_cluster_metrics_latest ON public.cluster_metrics USING btree (cluster, "timestamp" DESC);