CREATE TABLE public.datacenter_metrics (
	datacenter text NULL,
	"timestamp" timestamp NULL,
	total_memory_capacity_gb numeric(10, 2) NULL,
	total_memory_used_gb numeric(10, 2) NULL,
	total_storage_capacity_gb numeric(20, 4) NULL,
	total_used_storage_gb numeric(20, 4) NULL,
	total_cpu_ghz_capacity numeric(10, 2) NULL,
	total_cpu_ghz_used numeric(10, 2) NULL,
	disk_usage_avg_kbps numeric(15, 2) NULL,
	disk_usage_min_kbps numeric(15) NULL,
	disk_usage_max_kbps numeric(15) NULL,
	network_usage_avg_kbps numeric(15, 2) NULL,
	network_usage_min_kbps numeric(15) NULL,
	network_usage_max_kbps numeric(15) NULL,
	memory_usage_avg_perc numeric(7, 2) NULL,
	memory_usage_min_perc numeric(7, 2) NULL,
	memory_usage_max_perc numeric(7, 2) NULL,
	cpu_usage_avg_perc numeric(7, 2) NULL,
	cpu_usage_min_perc numeric(7, 2) NULL,
	cpu_usage_max_perc numeric(7, 2) NULL,
	total_host_count int4 NULL,
	total_vm_count int4 NULL,
	total_cluster_count int4 NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	dc varchar(50) NULL,
	CONSTRAINT unique_dc_timestamp_entry UNIQUE (datacenter, "timestamp")
);
CREATE INDEX idx_dc_metrics_latest ON public.datacenter_metrics USING btree (datacenter, "timestamp" DESC);