CREATE TABLE public.ibm_vios_network_virtual (
	servername varchar(255) NULL,
	viosname varchar(255) NULL,
	"location" varchar(255) NULL,
	vswitchid int4 NULL,
	vlanid int4 NULL,
	physicallocation varchar(255) NULL,
	isportvlanid bool NULL,
	receivedpackets float8 NULL,
	sentpackets float8 NULL,
	droppedpackets float8 NULL,
	sentbytes float8 NULL,
	receivedbytes float8 NULL,
	receivedphysicalpackets float8 NULL,
	sentphysicalpackets float8 NULL,
	droppedphysicalpackets float8 NULL,
	sentphysicalbytes float8 NULL,
	receivedphysicalbytes float8 NULL,
	transferredbytes float8 NULL,
	transferredphysicalbytes float8 NULL,
	"time" timestamptz NULL,
	CONSTRAINT unique_ibm_vios_network_virtual_metric_entry UNIQUE (viosname, vswitchid, vlanid, "time")
);