CREATE TABLE public.ibm_storage_mdsk_io (
	node_id text NULL,
	"timestamp" timestamp NULL,
	id text NULL,
	ro int8 NULL,
	wo int8 NULL,
	rb int8 NULL,
	wb int8 NULL,
	re int8 NULL,
	we int8 NULL,
	rq int8 NULL,
	wq int8 NULL,
	pre int8 NULL,
	pwe int8 NULL,
	ure int8 NULL,
	urq int8 NULL,
	uwq int8 NULL,
	uwe int8 NULL,
	storage_ip varchar(255) NULL
);