CREATE TABLE public.ibm_storage_host_by_id (
	id int4 NULL,
	"name" varchar(255) NULL,
	port_count int4 NULL,
	"type" varchar(100) NULL,
	iogrp_count int4 NULL,
	status varchar(50) NULL,
	site_id int4 NULL,
	site_name varchar(255) NULL,
	host_cluster_id int4 NULL,
	host_cluster_name varchar(255) NULL,
	protocol varchar(50) NULL,
	status_policy varchar(100) NULL,
	status_site varchar(100) NULL,
	nodes_wwpn varchar(255) NULL,
	nodes_node_logged_in_count int4 NULL,
	nodes_state varchar(100) NULL,
	owner_id int4 NULL,
	owner_name varchar(255) NULL,
	portset_id int4 NULL,
	portset_name varchar(255) NULL,
	"timestamp" timestamp NULL,
	storage_ip varchar(255) NULL
);