CREATE TABLE public.ibm_storage_vdsk_io (
	node_id text NULL,
	"timestamp" timestamp NULL,
	id text NULL,
	ro int8 NULL,
	wo int8 NULL,
	rb int8 NULL,
	wb int8 NULL,
	re int8 NULL,
	we int8 NULL,
	rq int8 NULL,
	wq int8 NULL,
	wxl int8 NULL,
	rxl int8 NULL,
	rl int8 NULL,
	wl int8 NULL,
	rlw int8 NULL,
	wlw int8 NULL,
	storage_ip varchar(255) NULL
);