CREATE TABLE public.ibm_storage_mdisk (
	id text NOT NULL,
	"name" text NULL,
	status text NULL,
	"mode" text NULL,
	mdisk_grp_id text NULL,
	mdisk_grp_name text NULL,
	capacity text NULL,
	"ctrl_LUN_#" text NULL,
	controller_name text NULL,
	uid text NULL,
	tier text NULL,
	encrypt text NULL,
	site_id text NULL,
	site_name text NULL,
	distributed text NULL,
	dedupe text NULL,
	over_provisioned text NULL,
	supports_unmap text NULL,
	"timestamp" timestamp DEFAULT now() NULL,
	storage_ip varchar(255) NULL
);