CREATE TABLE public.loki_platforms (
	id int4 NOT NULL,
	url text NULL,
	display_url text NULL,
	display text NULL,
	"name" text NULL,
	slug text NULL,
	manufacturer_id int4 NULL,
	manufacturer_url text NULL,
	manufacturer_display text NULL,
	manufacturer_name text NULL,
	manufacturer_slug text NULL,
	manufacturer_description text NULL,
	config_template text NULL,
	description text NULL,
	tags jsonb NULL,
	custom_fields_dc text NULL,
	custom_fields_ip_addresses text NULL,
	custom_fields_port text NULL,
	custom_fields_site text NULL,
	custom_fields_url text NULL,
	created timestamptz NULL,
	last_updated timestamptz NULL,
	device_count int4 NULL,
	virtualmachine_count int4 NULL,
	CONSTRAINT loki_platforms_pkey PRIMARY KEY (id)
);