CREATE TABLE public.loki_device_types (
	id int8 NOT NULL,
	url varchar(2048) NULL,
	display_url varchar(2048) NULL,
	display varchar(255) NULL,
	manufacturer_id int8 NULL,
	manufacturer_url varchar(2048) NULL,
	manufacturer_display varchar(255) NULL,
	manufacturer_name varchar(255) NULL,
	manufacturer_slug varchar(100) NULL,
	default_platform_id int8 NULL,
	default_platform_url varchar(2048) NULL,
	default_platform_display varchar(255) NULL,
	default_platform_name varchar(255) NULL,
	model varchar(255) NULL,
	slug varchar(100) NULL,
	part_number varchar(255) NULL,
	u_height float8 NULL,
	exclude_from_utilization bool NULL,
	is_full_depth bool NULL,
	subdevice_role varchar(255) NULL,
	airflow varchar(255) NULL,
	weight float8 NULL,
	weight_unit varchar(255) NULL,
	front_image varchar(2048) NULL,
	rear_image varchar(2048) NULL,
	description varchar(500) NULL,
	"comments" varchar(500) NULL,
	tags jsonb NULL,
	custom_fields jsonb NULL,
	created timestamptz NULL,
	last_updated timestamptz NULL,
	device_count int4 NULL,
	console_port_template_count int4 NULL,
	console_server_port_template_count int4 NULL,
	power_port_template_count int4 NULL,
	power_outlet_template_count int4 NULL,
	interface_template_count int4 NULL,
	front_port_template_count int4 NULL,
	rear_port_template_count int4 NULL,
	device_bay_template_count int4 NULL,
	module_bay_template_count int4 NULL,
	inventory_item_template_count int4 NULL
);
CREATE UNIQUE INDEX ux_loki_device_types_id ON public.loki_device_types USING btree (id);