CREATE TABLE public.nutanix_vm_metrics (
	vm_name varchar(255) NOT NULL,
	vm_uuid uuid NOT NULL,
	cluster_uuid uuid NOT NULL,
	host_name varchar(255) NULL,
	host_uuid uuid NULL,
	power_state varchar(10) NULL,
	memory_capacity int8 NULL,
	cpu_count int4 NULL,
	disk_capacity int8 NULL,
	hypervisor_read_io_bandwidth_min int8 NULL,
	hypervisor_read_io_bandwidth_max int8 NULL,
	hypervisor_read_io_bandwidth_avg int8 NULL,
	hypervisor_write_io_bandwidth_min int8 NULL,
	hypervisor_write_io_bandwidth_max int8 NULL,
	hypervisor_write_io_bandwidth_avg int8 NULL,
	cpu_usage_min int8 NULL,
	cpu_usage_max int8 NULL,
	cpu_usage_avg int8 NULL,
	memory_usage_min int8 NULL,
	memory_usage_max int8 NULL,
	memory_usage_avg int8 NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	used_storage int8 NULL,
	guest_os varchar NULL,
	power_usage numeric NULL,
	CONSTRAINT unique_nutanix_vm_metric_entry UNIQUE (vm_uuid, collection_time)
);
CREATE INDEX index_nutanix_vm_metric ON public.nutanix_vm_metrics USING btree (vm_name, collection_time);