CREATE TABLE public.nutanix_host_metrics (
	id serial4 NOT NULL,
	host_name varchar(255) NOT NULL,
	host_uuid varchar(255) NOT NULL,
	cluster_uuid varchar(255) NOT NULL,
	total_memory_capacity int8 NOT NULL,
	total_cpu_capacity int8 NOT NULL,
	num_cpu_cores int4 NOT NULL,
	total_vms int4 NOT NULL,
	network_transmitted_avg int8 NULL,
	network_received_avg int8 NULL,
	memory_usage_min int8 NULL,
	memory_usage_max int8 NULL,
	memory_usage_avg int8 NULL,
	cpu_usage_min int8 NULL,
	cpu_usage_max int8 NULL,
	cpu_usage_avg int8 NULL,
	storage_capacity int8 NOT NULL,
	storage_usage int8 NOT NULL,
	read_io_bandwidth_min int8 NULL,
	read_io_bandwidth_max int8 NULL,
	read_io_bandwidth_avg int8 NULL,
	write_io_bandwidth_min int8 NULL,
	write_io_bandwidth_max int8 NULL,
	write_io_bandwidth_avg int8 NULL,
	collectiontime timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	boottime int8 NULL,
	CONSTRAINT unique_nutanix_host_metric_entry UNIQUE (host_uuid, collectiontime)
);