CREATE TABLE public.nutanix_snapshot_schedule_metrics (
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	nutanix_ip varchar(255) NULL,
	protection_domain_name varchar(255) NULL,
	state varchar(255) NULL,
	missing_entities_entity_name text NULL,
	missing_entities_entity_type text NULL,
	missing_entities_cg_name text NULL,
	size_in_bytes int8 NULL,
	vm_names text NULL,
	schedule_type varchar(255) NULL,
	schedule_every_nth int4 NULL,
	schedule_start_times_in_usecs int8 NULL,
	schedule_end_time_in_usecs int8 NULL,
	schedule_local_max_snapshots int4 NULL,
	schedule_remote_max_snapshots jsonb NULL,
	exclusive_usage_in_bytes int8 NULL,
	snapshot_id varchar(255) NULL,
	snapshot_create_time_usecs int8 NULL,
	snapshot_expiry_time_usecs int8 NULL,
	schedule_user_start_time_in_usecs int8 NULL,
	schedule_id varchar(255) NULL,
	schedule_suspended bool NULL,
	schedule_local_retention_period int8 NULL,
	schedule_remote_retention_period jsonb NULL,
	schedule_local_retention_type varchar(255) NULL,
	schedule_remote_retention_type varchar(255) NULL,
	CONSTRAINT unique_snapshot_identity UNIQUE (nutanix_ip, protection_domain_name, snapshot_id, snapshot_create_time_usecs)
);