CREATE TABLE public.raw_netbackup_jobs_metrics_old (
	data_type varchar(50) NOT NULL,
	collection_timestamp timestamptz NOT NULL,
	netbackup_host varchar(50) DEFAULT ''::character varying NOT NULL,
	id varchar(255) NOT NULL,
	"type" varchar(50) NULL,
	jobid varchar(255) NULL,
	parentjobid varchar(255) NULL,
	activeprocessid varchar(255) NULL,
	jobtype varchar(100) NULL,
	jobsubtype varchar(100) NULL,
	policytype varchar(100) NULL,
	policyname varchar(255) NULL,
	scheduletype varchar(100) NULL,
	schedulename varchar(255) NULL,
	clientname varchar(255) NULL,
	jobowner varchar(255) NULL,
	jobgroup varchar(255) NULL,
	backupid varchar(255) NULL,
	destinationstorageunitname varchar(255) NULL,
	destinationmediaservername varchar(255) NULL,
	datamovement varchar(100) NULL,
	streamnumber int4 NULL,
	copynumber int4 NULL,
	priority int4 NULL,
	"compression" int4 NULL,
	state varchar(100) NULL,
	numberoffiles int8 NULL,
	estimatedfiles int8 NULL,
	kilobytestransferred int8 NULL,
	kilobytestotransfer int8 NULL,
	transferrate numeric(10, 2) NULL,
	percentcomplete numeric(5, 2) NULL,
	restartable bool NULL,
	suspendable bool NULL,
	resumable bool NULL,
	frozenimage bool NULL,
	transporttype varchar(100) NULL,
	currentoperation int4 NULL,
	sessionid varchar(255) NULL,
	numberoftapetoeject int4 NULL,
	submissiontype int4 NULL,
	auditdomaintype int4 NULL,
	starttime timestamptz NULL,
	endtime timestamptz NULL,
	activetrystarttime timestamptz NULL,
	lastupdatetime timestamptz NULL,
	childcount int4 NULL,
	jobpath varchar(500) NULL,
	retentionlevel int4 NULL,
	try int4 NULL,
	cancellable bool NULL,
	jobqueuereason int4 NULL,
	kilobytesdatatransferred int8 NULL,
	elapsedtime varchar(50) NULL,
	activeelapsedtime varchar(50) NULL,
	dtemode varchar(100) NULL,
	workloaddisplayname varchar(255) NULL,
	offhosttype varchar(100) NULL,
	dedupratio numeric(5, 2) NULL,
	status int4 NULL,
	profilename varchar(255) NULL,
	dedupspaceratio numeric(5, 2) NULL,
	compressionspaceratio numeric(5, 2) NULL,
	CONSTRAINT netbackup_jobs_metrics_pkey PRIMARY KEY (id, collection_timestamp)
);
CREATE INDEX idx_netbackup_jobs_client ON public.raw_netbackup_jobs_metrics_old USING btree (clientname);