CREATE TABLE public.raw_zerto_vpg_metrics (
	data_type varchar(50) NOT NULL,
	collection_timestamp timestamptz NOT NULL,
	zerto_host varchar(50) DEFAULT ''::character varying NOT NULL,
	id varchar(255) NOT NULL,
	"name" varchar(255) NULL,
	status int4 NULL,
	actualrpo int4 NULL,
	vmscount int4 NULL,
	alertstatus int4 NULL,
	priority int4 NULL,
	source_site varchar(255) NULL,
	target_site varchar(255) NULL,
	vm_identifiers jsonb NULL,
	iops int4 NULL,
	throughput_mb numeric(10, 4) NULL,
	provisioned_storage_mb int8 NULL,
	used_storage_mb int8 NULL,
	CONSTRAINT zerto_vpg_metrics_pkey PRIMARY KEY (id, collection_timestamp)
);