CREATE TABLE public.raw_panduit_pdu_inventory (
	id int4 DEFAULT nextval('panduit_pdu_inventory_id_seq'::regclass) NOT NULL,
	collection_timestamp timestamptz NOT NULL,
	pdu_id int4 NOT NULL,
	pdu_name varchar(255) NULL,
	zabbix_host_name varchar(255) NULL,
	"location" varchar(50) NULL,
	rack_id varchar(50) NULL,
	pdu_index varchar(50) NULL,
	device_model varchar(255) NULL,
	firmware_version varchar(50) NULL,
	hardware_version varchar(50) NULL,
	system_name varchar(255) NULL,
	breaker_count int4 NULL,
	outlet_count int4 NULL,
	door_count int4 NULL,
	dry_count int4 NULL,
	hid_count int4 NULL,
	humidity_count int4 NULL,
	input_phase_count int4 NULL,
	rope_count int4 NULL,
	spot_count int4 NULL,
	temperature_count int4 NULL,
	CONSTRAINT panduit_pdu_inventory_pkey PRIMARY KEY (id),
	CONSTRAINT uq_panduit_inventory_pdu_timestamp UNIQUE (pdu_id, collection_timestamp)
);
CREATE INDEX idx_panduit_inventory_pdu_id_timestamp ON public.raw_panduit_pdu_inventory USING btree (pdu_id, collection_timestamp DESC);