CREATE TABLE public.raw_brocade_port_statistics (
	switch_host varchar(255) NOT NULL,
	collection_timestamp timestamptz NOT NULL,
	"name" varchar(50) NOT NULL,
	time_difference_seconds float8 NULL,
	in_octets int8 NULL,
	out_octets int8 NULL,
	in_frames int8 NULL,
	out_frames int8 NULL,
	crc_errors int8 NULL,
	class_3_discards int8 NULL,
	link_failures int8 NULL,
	loss_of_signal int8 NULL,
	loss_of_sync int8 NULL,
	invalid_transmission_words int8 NULL,
	in_octets_delta int8 NULL,
	out_octets_delta int8 NULL,
	in_frames_delta int8 NULL,
	out_frames_delta int8 NULL,
	crc_errors_delta int8 NULL,
	class_3_discards_delta int8 NULL,
	link_failures_delta int8 NULL,
	loss_of_signal_delta int8 NULL,
	loss_of_sync_delta int8 NULL,
	invalid_transmission_words_delta int8 NULL,
	in_rate int8 NULL,
	out_rate int8 NULL,
	CONSTRAINT brocade_port_statistics_pkey PRIMARY KEY (switch_host, collection_timestamp, name)
);