CREATE TABLE public.raw_brocade_port_status (
	switch_host varchar(255) NOT NULL,
	collection_timestamp timestamptz NOT NULL,
	"name" varchar(50) NOT NULL,
	wwn varchar(23) NULL,
	port_type int4 NULL,
	speed int8 NULL,
	max_speed int8 NULL,
	user_friendly_name varchar(255) NULL,
	operational_status int4 NULL,
	is_enabled_state bool NULL,
	auto_negotiate int4 NULL,
	isl_ready_mode_enabled int4 NULL,
	long_distance int4 NULL,
	trunk_port_enabled int4 NULL,
	vc_link_init int4 NULL,
	pod_license_status bool NULL,
	default_index int4 NULL,
	fcid int4 NULL,
	fcid_hex varchar(10) NULL,
	physical_state varchar(50) NULL,
	persistent_disable int4 NULL,
	g_port_locked int4 NULL,
	e_port_disable int4 NULL,
	ex_port_enabled int4 NULL,
	npiv_enabled int4 NULL,
	qos_enabled int4 NULL,
	fec_enabled int4 NULL,
	fec_active int4 NULL,
	credit_recovery_enabled int4 NULL,
	credit_recovery_active int4 NULL,
	neighbor_node_wwn varchar(23) NULL,
	CONSTRAINT brocade_port_status_pkey PRIMARY KEY (switch_host, collection_timestamp, name)
);