CREATE TABLE public.raw_netbackup_disk_pools_metrics (
	data_type varchar(50) NOT NULL,
	collection_timestamp timestamptz NOT NULL,
	netbackup_host varchar(50) DEFAULT ''::character varying NOT NULL,
	id varchar(255) NOT NULL,
	"type" varchar(50) NULL,
	"name" varchar(255) NULL,
	stype varchar(100) NULL,
	storagecategory varchar(100) NULL,
	diskvolumes_name varchar(255) NULL,
	diskvolumes_id varchar(255) NULL,
	diskvolumes_diskmediaid varchar(255) NULL,
	diskvolumes_state varchar(100) NULL,
	diskvolumes_rawsizebytes int8 NULL,
	diskvolumes_freesizebytes int8 NULL,
	diskvolumes_isreplicationsource bool NULL,
	diskvolumes_isreplicationtarget bool NULL,
	diskvolumes_wormindelibleminimuminterval int4 NULL,
	diskvolumes_wormindeliblemaximuminterval int4 NULL,
	highwatermark int4 NULL,
	lowwatermark int4 NULL,
	max_limitiostreams int4 NULL,
	diskpoolstate varchar(100) NULL,
	rawsizebytes int8 NULL,
	usablesizebytes int8 NULL,
	availablespacebytes int8 NULL,
	usedcapacitybytes int8 NULL,
	wormcapable bool NULL,
	readonly bool NULL,
	mediaserverscount int4 NULL,
	CONSTRAINT netbackup_disk_pools_metrics_pkey PRIMARY KEY (id, collection_timestamp)
);
CREATE INDEX idx_netbackup_pools_type ON public.raw_netbackup_disk_pools_metrics USING btree (stype);