CREATE TABLE public.vm_metrics (
	datacenter text NULL,
	"cluster" text NULL,
	vmhost text NULL,
	vmname text NOT NULL,
	"timestamp" timestamp NOT NULL,
	number_of_cpus int4 NULL,
	cpu_usage_avg_mhz numeric(10, 2) NULL,
	cpu_usage_min_mhz numeric(10, 2) NULL,
	cpu_usage_max_mhz numeric(10, 2) NULL,
	memory_usage_avg_perc numeric(5, 2) NULL,
	memory_usage_min_perc numeric(5, 2) NULL,
	memory_usage_max_perc numeric(5, 2) NULL,
	disk_usage_avg_kbps numeric(10, 2) NULL,
	disk_usage_min_kbps numeric(10, 2) NULL,
	disk_usage_max_kbps numeric(10, 2) NULL,
	guest_os text NULL,
	datastore text NULL,
	used_space_gb numeric(10, 2) NULL,
	provisioned_space_gb numeric(10, 2) NULL,
	folder text NULL,
	"uuid" text NOT NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	total_cpu_capacity_mhz numeric(20, 4) NULL,
	total_memory_capacity_gb numeric(20, 4) NULL,
	esxi_system_uuid varchar(36) NULL,
	boottime varchar(255) NULL,
	CONSTRAINT unique_vm_timestamp UNIQUE (datacenter, cluster, vmhost, uuid, "timestamp")
);
CREATE INDEX idx_vm_metrics_latest ON public.vm_metrics USING btree (uuid, "timestamp" DESC);