CREATE TABLE public.vmhost_metrics (
	datacenter text NULL,
	"cluster" text NULL,
	vmhost text NULL,
	"timestamp" timestamp NULL,
	esxi_system_uuid text NULL,
	esxi_bios_uuid text NULL,
	cpu_ghz_capacity numeric(10, 2) NULL,
	cpu_ghz_used numeric(10, 2) NULL,
	cpu_ghz_free numeric(10, 2) NULL,
	memory_capacity_gb numeric(10, 2) NULL,
	memory_used_gb numeric(10, 2) NULL,
	memory_free_gb numeric(10, 2) NULL,
	disk_usage_avg_kbps numeric(15, 2) NULL,
	disk_usage_min_kbps numeric(15) NULL,
	disk_usage_max_kbps numeric(15) NULL,
	network_usage_avg_kbps numeric(15, 2) NULL,
	network_usage_min_kbps numeric(15) NULL,
	network_usage_max_kbps numeric(15) NULL,
	memory_usage_avg_perc numeric(7, 2) NULL,
	memory_usage_min_perc numeric(7, 2) NULL,
	memory_usage_max_perc numeric(7, 2) NULL,
	cpu_usage_avg_perc numeric(7, 2) NULL,
	cpu_usage_min_perc numeric(7, 2) NULL,
	cpu_usage_max_perc numeric(7, 2) NULL,
	total_freespacegb numeric(20, 2) NULL,
	total_capacitygb numeric(20, 2) NULL,
	collection_time timestamp DEFAULT CURRENT_TIMESTAMP NULL,
	power_usage numeric NULL,
	uptime varchar(255) NULL,
	CONSTRAINT unique_vmhost_timestamp UNIQUE (datacenter, cluster, vmhost, "timestamp")
);
CREATE INDEX idx_host_metrics_latest ON public.vmhost_metrics USING btree (esxi_bios_uuid, "timestamp" DESC);