apiVersion: v1
kind: ConfigMap
metadata:
  name: bulutistan-frontend-config
data:
  DATACENTER_API_URL: "http://bulutistan-datacenter-api"
  CUSTOMER_API_URL: "http://bulutistan-customer-api"
  QUERY_API_URL: "http://bulutistan-query-api"
