apiVersion: v1
kind: Service
metadata:
  name: bulutistan-frontend
  labels:
    app: bulutistan-frontend
spec:
  type: ClusterIP
  selector:
    app: bulutistan-frontend
  ports:
    - port: 80
      targetPort: 8050
      protocol: TCP
