apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bulutistan-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  rules:
    - host: bulutistan.local
      http:
        paths:
          - path: /api/v1/sla
            pathType: Prefix
            backend:
              service:
                name: bulutistan-datacenter-api
                port:
                  number: 80
          - path: /api/v1/physical-inventory
            pathType: Prefix
            backend:
              service:
                name: bulutistan-datacenter-api
                port:
                  number: 80
          - path: /api/v1/datacenters
            pathType: Prefix
            backend:
              service:
                name: bulutistan-datacenter-api
                port:
                  number: 80
          - path: /api/v1/dashboard
            pathType: Prefix
            backend:
              service:
                name: bulutistan-datacenter-api
                port:
                  number: 80
          - path: /api/v1/customers
            pathType: Prefix
            backend:
              service:
                name: bulutistan-customer-api
                port:
                  number: 80
          - path: /api/v1/queries
            pathType: Prefix
            backend:
              service:
                name: bulutistan-query-api
                port:
                  number: 80
          - path: /health
            pathType: Exact
            backend:
              service:
                name: bulutistan-datacenter-api
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bulutistan-frontend
                port:
                  number: 80
