apiVersion: v1
kind: Service
metadata:
  name: datalake-data-api
  labels:
    app: datalake-data-api
spec:
  type: ClusterIP
  selector:
    app: datalake-data-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
